name: restricted-marker-transfer

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.71.1-x86_64-unknown-linux-gnu
          default: true
          components: clippy, rustfmt
      - name: cargo format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - name: cargo tarpaulin xml report
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.26.1'
          out-type: Xml
          args: '--ignore-tests'
      - name: upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
      - name: archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: cobertura.xml
  release:
    needs: check
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: optimize
        run: make optimize
      - name : release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            artifacts/restricted_marker_transfer.wasm
            artifacts/checksums.txt
